[2021-11-27 00:10:26,279] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 00:10:26,284] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 00:10:26,284] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 00:10:26,284] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-27 00:10:26,285] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 00:10:26,291] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): scraping> on 2021-11-26 00:00:00+00:00
[2021-11-27 00:10:26,293] {standard_task_runner.py:52} INFO - Started process 11905 to run task
[2021-11-27 00:10:26,298] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial', 'scraping', 'scheduled__2021-11-26T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/tutorial.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpjdwafk5b', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpozo243b2']
[2021-11-27 00:10:26,300] {standard_task_runner.py:77} INFO - Job 3: Subtask scraping
[2021-11-27 00:10:26,327] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 00:10:26,356] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=scraping
AIRFLOW_CTX_EXECUTION_DATE=2021-11-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-26T00:00:00+00:00
[2021-11-27 00:10:26,357] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 00:10:26,357] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/scraping.py down']
[2021-11-27 00:10:26,363] {subprocess.py:85} INFO - Output:
[2021-11-27 00:13:26,610] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 11905
[2021-11-27 00:13:26,613] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-27 00:13:26,617] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2021-11-27 00:13:26,643] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 00:13:26,656] {taskinstance.py:1270} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=scraping, execution_date=20211126T000000, start_date=20211126T171026, end_date=20211126T171326
[2021-11-27 00:13:26,672] {standard_task_runner.py:88} ERROR - Failed to execute job 3 for task scraping
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 00:13:26,705] {process_utils.py:66} INFO - Process psutil.Process(pid=11905, status='terminated', exitcode=1, started='00:10:26') (11905) terminated with exit code 1
[2021-11-27 00:13:26,706] {process_utils.py:66} INFO - Process psutil.Process(pid=11906, status='terminated', started='00:10:26') (11906) terminated with exit code None
[2021-11-27 00:14:45,730] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 00:14:45,739] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 00:14:45,739] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 00:14:45,739] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-27 00:14:45,739] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 00:14:45,748] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): scraping> on 2021-11-26 00:00:00+00:00
[2021-11-27 00:14:45,751] {standard_task_runner.py:52} INFO - Started process 12008 to run task
[2021-11-27 00:14:45,756] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial', 'scraping', 'scheduled__2021-11-26T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/tutorial.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpms00soau', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmp_esj2kl3']
[2021-11-27 00:14:45,759] {standard_task_runner.py:77} INFO - Job 2: Subtask scraping
[2021-11-27 00:14:45,792] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 00:14:45,821] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=scraping
AIRFLOW_CTX_EXECUTION_DATE=2021-11-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-26T00:00:00+00:00
[2021-11-27 00:14:45,822] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 00:14:45,823] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/scraping.py /Users/Home/Airflow/down']
[2021-11-27 00:14:45,829] {subprocess.py:85} INFO - Output:
[2021-11-27 00:27:24,687] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 12008
[2021-11-27 00:27:24,691] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-27 00:27:24,695] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2021-11-27 00:27:24,728] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 00:27:24,742] {taskinstance.py:1270} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=scraping, execution_date=20211126T000000, start_date=20211126T171445, end_date=20211126T172724
[2021-11-27 00:27:24,757] {standard_task_runner.py:88} ERROR - Failed to execute job 2 for task scraping
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 00:27:24,787] {process_utils.py:66} INFO - Process psutil.Process(pid=12009, status='terminated', started='00:14:45') (12009) terminated with exit code None
[2021-11-27 00:27:24,787] {process_utils.py:66} INFO - Process psutil.Process(pid=12008, status='terminated', exitcode=1, started='00:14:45') (12008) terminated with exit code 1
[2021-11-27 00:28:14,856] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 00:28:14,861] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 00:28:14,862] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 00:28:14,862] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-27 00:28:14,862] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 00:28:14,869] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): scraping> on 2021-11-26 00:00:00+00:00
[2021-11-27 00:28:14,871] {standard_task_runner.py:52} INFO - Started process 12274 to run task
[2021-11-27 00:28:14,876] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial', 'scraping', 'scheduled__2021-11-26T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/tutorial.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpn5zebhhv', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmp03mhzdh1']
[2021-11-27 00:28:14,877] {standard_task_runner.py:77} INFO - Job 2: Subtask scraping
[2021-11-27 00:28:14,906] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.scraping scheduled__2021-11-26T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 00:28:14,936] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=scraping
AIRFLOW_CTX_EXECUTION_DATE=2021-11-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-26T00:00:00+00:00
[2021-11-27 00:28:14,936] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 00:28:14,937] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/scraping.py /Users/Home/Airflow/down']
[2021-11-27 00:28:14,943] {subprocess.py:85} INFO - Output:
[2021-11-27 00:37:39,462] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa does not match this instance's hostname MacBookPro.local
[2021-11-27 00:37:39,471] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 12274
[2021-11-27 00:37:39,473] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-27 00:37:39,475] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2021-11-27 00:37:39,497] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 00:37:39,506] {taskinstance.py:1270} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=scraping, execution_date=20211126T000000, start_date=20211126T172814, end_date=20211126T173739
[2021-11-27 00:37:39,518] {standard_task_runner.py:88} ERROR - Failed to execute job 2 for task scraping
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 00:37:39,529] {process_utils.py:66} INFO - Process psutil.Process(pid=12275, status='terminated', started='00:28:14') (12275) terminated with exit code None
[2021-11-27 00:37:39,530] {process_utils.py:66} INFO - Process psutil.Process(pid=12274, status='terminated', exitcode=1, started='00:28:14') (12274) terminated with exit code 1
