[2021-11-27 09:45:35,263] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 09:45:35,268] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 09:45:35,268] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 09:45:35,268] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-11-27 09:45:35,268] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 09:45:35,275] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): scraping> on 2021-11-26 00:00:00+00:00
[2021-11-27 09:45:35,277] {standard_task_runner.py:52} INFO - Started process 4742 to run task
[2021-11-27 09:45:35,281] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'daily-scraping', 'scraping', 'scheduled__2021-11-26T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/scraping.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpluoh7wis', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpb_f15o2z']
[2021-11-27 09:45:35,284] {standard_task_runner.py:77} INFO - Job 216: Subtask scraping
[2021-11-27 09:45:35,312] {logging_mixin.py:109} INFO - Running <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 09:45:35,337] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=daily-scraping
AIRFLOW_CTX_TASK_ID=scraping
AIRFLOW_CTX_EXECUTION_DATE=2021-11-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-26T00:00:00+00:00
[2021-11-27 09:45:35,338] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 09:45:35,339] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/scraping.py /Users/Home/Airflow/down']
[2021-11-27 09:45:35,345] {subprocess.py:85} INFO - Output:
[2021-11-27 09:50:52,707] {local_task_job.py:206} WARNING - Recorded pid 5055 does not match the current pid 4742
[2021-11-27 09:50:52,716] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 4742
[2021-11-27 09:50:52,717] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-27 09:50:52,719] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2021-11-27 09:50:52,729] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 09:50:52,738] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=daily-scraping, task_id=scraping, execution_date=20211126T000000, start_date=20211127T025051, end_date=20211127T025052
[2021-11-27 09:50:52,751] {standard_task_runner.py:88} ERROR - Failed to execute job 216 for task scraping
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 09:50:52,772] {process_utils.py:66} INFO - Process psutil.Process(pid=4742, status='terminated', exitcode=1, started='09:45:35') (4742) terminated with exit code 1
[2021-11-27 09:50:52,773] {process_utils.py:66} INFO - Process psutil.Process(pid=4743, status='terminated', started='09:45:35') (4743) terminated with exit code None
[2021-11-27 11:31:13,020] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 11:31:13,027] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 11:31:13,027] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 11:31:13,027] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-11-27 11:31:13,027] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 11:31:13,034] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): scraping> on 2021-11-26 00:00:00+00:00
[2021-11-27 11:31:13,036] {standard_task_runner.py:52} INFO - Started process 10830 to run task
[2021-11-27 11:31:13,042] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'daily-scraping', 'scraping', 'scheduled__2021-11-26T00:00:00+00:00', '--job-id', '541', '--raw', '--subdir', 'DAGS_FOLDER/scraping.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpmhy_vjfp', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpo6x4vhbc']
[2021-11-27 11:31:13,044] {standard_task_runner.py:77} INFO - Job 541: Subtask scraping
[2021-11-27 11:31:13,070] {logging_mixin.py:109} INFO - Running <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 11:31:13,093] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=daily-scraping
AIRFLOW_CTX_TASK_ID=scraping
AIRFLOW_CTX_EXECUTION_DATE=2021-11-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-26T00:00:00+00:00
[2021-11-27 11:31:13,093] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 11:31:13,094] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/scraping.py /Users/Home/Airflow/down']
[2021-11-27 11:31:13,099] {subprocess.py:85} INFO - Output:
[2021-11-27 11:31:18,093] {local_task_job.py:211} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2021-11-27 11:31:18,099] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 10830
[2021-11-27 11:31:18,099] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-27 11:31:18,099] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2021-11-27 11:31:18,129] {process_utils.py:66} INFO - Process psutil.Process(pid=10831, status='terminated', started='11:31:13') (10831) terminated with exit code None
[2021-11-27 11:31:18,129] {process_utils.py:66} INFO - Process psutil.Process(pid=10830, status='terminated', exitcode=0, started='11:31:13') (10830) terminated with exit code 0
[2021-11-27 17:12:15,618] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 17:12:15,627] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [queued]>
[2021-11-27 17:12:15,627] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 17:12:15,627] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-11-27 17:12:15,627] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 17:12:15,635] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): scraping> on 2021-11-26 00:00:00+00:00
[2021-11-27 17:12:15,637] {standard_task_runner.py:52} INFO - Started process 21115 to run task
[2021-11-27 17:12:15,642] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'daily-scraping', 'scraping', 'scheduled__2021-11-26T00:00:00+00:00', '--job-id', '1152', '--raw', '--subdir', 'DAGS_FOLDER/scraping.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpj7313z62', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmp01uh0ekn']
[2021-11-27 17:12:15,644] {standard_task_runner.py:77} INFO - Job 1152: Subtask scraping
[2021-11-27 17:12:15,671] {logging_mixin.py:109} INFO - Running <TaskInstance: daily-scraping.scraping scheduled__2021-11-26T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 17:12:15,695] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=daily-scraping
AIRFLOW_CTX_TASK_ID=scraping
AIRFLOW_CTX_EXECUTION_DATE=2021-11-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-26T00:00:00+00:00
[2021-11-27 17:12:15,696] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 17:12:15,696] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/scraping.py /Users/Home/Airflow/down']
[2021-11-27 17:12:15,701] {subprocess.py:85} INFO - Output:
[2021-11-27 17:26:37,061] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa does not match this instance's hostname MacBookPro.local
[2021-11-27 17:26:37,071] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 21115
[2021-11-27 17:26:37,073] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-27 17:26:37,076] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2021-11-27 17:26:37,099] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 17:26:37,107] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=daily-scraping, task_id=scraping, execution_date=20211126T000000, start_date=20211127T101215, end_date=20211127T102637
[2021-11-27 17:26:37,128] {standard_task_runner.py:88} ERROR - Failed to execute job 1152 for task scraping
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-27 17:26:37,175] {process_utils.py:66} INFO - Process psutil.Process(pid=21116, status='terminated', started='17:12:15') (21116) terminated with exit code None
[2021-11-27 17:26:37,176] {process_utils.py:66} INFO - Process psutil.Process(pid=21115, status='terminated', exitcode=1, started='17:12:15') (21115) terminated with exit code 1
